version: "3.4"

services:
  client:
    image: arianvaldivieso/vite
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:5173
    volumes:
      - ./:/app

